
---
- hosts: office
  tasks:
  - name: création d'un utilisateur
    user:
      name: itesciadmin1
      create_home: yes
  - name: Déployer le package
    package:
      name: htop
      state: present
 

