
---
#test
- hosts: 
  - office
  - backup
  vars:
    list_users:
      - toto1
      - titi1
      - tata1 
  tasks:
  - name: création d'un utilisateur
    user:
      name: "{{ item }}"
      shell: /bin/bash
      create_home: yes
    loop: "{{ list_users }}"
 

  - name: Déployer le package
    package:
      name: vim
      state: present
 
  - name: clé SSH
    authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
 
    loop: "{{ list_users }}"



